- id: '1568784959927'
  alias: Match hallway lights to living room lights
  trigger:
  - entity_id: binary_sensor.hallway_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.living_room_ceiling_4
    state: 'on'
  action:
  - alias: ''
    service: light.turn_on
    entity_id:
    - light.hallway_1
    - light.hallway_2
    data_template:
      brightness: '{{ states.light.living_room_ceiling_4.attributes.brightness }}'
      color_temp: '{{ states.light.living_room_ceiling_4.attributes.color_temp }}'
- id: '1568831881438'
  alias: Outdoor lights - on at sunset
  trigger:
  - event: sunset
    offset: -00:45:00
    platform: sun
  condition: []
  action:
  - data:
      brightness: 254
      entity_id: light.outside
      rgb_color:
      - 255
      - 207
      - 120
    service: light.turn_on
- id: '1568831954351'
  alias: Outdoor lights - off at sunrise
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - data:
      entity_id: light.outside
    service: light.turn_off
- id: '1568832400745'
  alias: Shades - Close 15 minutes after sunset
  trigger:
  - event: sunset
    offset: +00:15:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: cover.serena_r_roller_shade
    service: cover.close_cover
  - data:
      entity_id: cover.serena_r_roller_shade_2
      position: 0
    service: cover.set_cover_position
- id: '1568834500654'
  alias: Computer - turn on weekday evenings when I come home
  trigger:
  - entity_id: person.raspberrypisauce
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - after: '16:00:00'
    before: '22:30:00'
    condition: time
  action:
  - data:
      entity_id: switch.computer
    service: switch.turn_on
- id: '1569304361436'
  alias: Evening door unlock - Turn on lights
  trigger:
  - entity_id: lock.back_door_lock
    from: locked
    platform: state
    to: unlocked
  - entity_id: lock.front_door_lock
    from: locked
    platform: state
    to: unlocked
  condition:
  - after: sunset
    after_offset: -01:00:00
    condition: sun
  - after: '15:00:00'
    before: '23:00:00'
    condition: time
  - condition: state
    entity_id: light.living_room
    state: 'off'
  action:
  - data:
      brightness: 255
      color_temp: 370
      entity_id:
      - light.living_room
      - light.kitchen
      - light.hallway
      - light.dining_room
    service: light.turn_on
- id: '1569304972806'
  alias: Night door unlock - turn on lights (after 11pm)
  trigger:
  - entity_id: lock.back_door_lock
    from: locked
    platform: state
    to: unlocked
  - entity_id: lock.front_door_lock
    from: locked
    platform: state
    to: unlocked
  condition:
  - after: '23:00:01'
    before: 04:00:00
    condition: time
  - condition: state
    entity_id: light.living_room
    state: 'off'
  action:
  - data:
      brightness: 26
      color_temp: 370
      entity_id:
      - light.living_room
      - light.kitchen
      - light.hallway
      - light.dining_room
    service: light.turn_on
- id: '1569996471447'
  alias: Shades - Open at 9:30am if I'm away
  trigger:
  - at: 09:30:00
    platform: time
  condition:
  - condition: state
    entity_id: cover.serena_r_roller_shade
    state: closed
  - condition: state
    entity_id: person.raspberrypisauce
    state: Away
  action:
  - data:
      entity_id:
      - cover.serena_r_roller_shade
      - cover.serena_r_roller_shade_2
    service: cover.open_cover
