- id: '1568784959927'
  alias: Match hallway lights to living room lights
  trigger:
  - entity_id: binary_sensor.hallway_motion
    platform: state
    to: 'on'
  - entity_id: binary_sensor.hallway_motion
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: light.living_room_ceiling_4
    state: 'on'
  action:
  - alias: ''
    data_template:
      brightness: '{{ states.light.living_room_ceiling_4.attributes.brightness }}'
      color_temp: '{{ states.light.living_room_ceiling_4.attributes.color_temp }}'
    entity_id:
    - light.hallway_1
    - light.hallway_2
    service: light.turn_on
- id: '1568831881438'
  alias: Outdoor lights - on at sunset
  trigger:
  - event: sunset
    offset: -00:45:00
    platform: sun
  condition: []
  action:
  - data:
      brightness: 254
      entity_id: light.outside
      rgb_color:
      - 255
      - 207
      - 120
    service: light.turn_on
- id: '1568831954351'
  alias: Outdoor lights - off at sunrise
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - data:
      entity_id: light.outside
    service: light.turn_off
- id: '1568832400745'
  alias: Shades - Close after sunset
  trigger:
  - event: sunset
    offset: +00:10:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: cover.serena_r_roller_shade
    service: cover.close_cover
  - data:
      entity_id: cover.serena_r_roller_shade_2
      position: 0
    service: cover.set_cover_position
- id: '1568834500654'
  alias: Computer - turn on weekday evenings when I come home
  trigger:
  - entity_id: person.raspberrypisauce
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - after: '16:00:00'
    before: '22:30:00'
    condition: time
  action:
  - data:
      entity_id: switch.computer
    service: switch.turn_on
- id: '1569304361436'
  alias: Lock - Turn on interior lights after sunset
  description: If the door is unlocked after sunset, turn on all interior lights if
    they're off.
  trigger:
  - entity_id: lock.back_door_lock
    from: locked
    platform: state
    to: unlocked
  - entity_id: lock.front_door_lock
    from: locked
    platform: state
    to: unlocked
  condition:
  - after: sunset
    after_offset: -01:00:00
    condition: sun
  - after: '15:00:00'
    before: '23:00:00'
    condition: time
  - condition: state
    entity_id: light.living_room
    state: 'off'
  action:
  - data:
      group_name: Common areas & bedroom
      scene_name: Bright
    service: hue.hue_activate_scene
- id: '1569304972806'
  alias: Night door unlock - turn on lights (after 11pm)
  trigger:
  - entity_id: lock.back_door_lock
    from: locked
    platform: state
    to: unlocked
  - entity_id: lock.front_door_lock
    from: locked
    platform: state
    to: unlocked
  condition:
  - after: '23:00:01'
    before: 02:00:00
    condition: time
  - condition: state
    entity_id: light.living_room
    state: 'off'
  action:
  - data:
      group_name: Common areas & bedroom
      scene_name: Evening
    service: hue.hue_activate_scene
- id: '1569996471447'
  alias: Shades - Open at 9:30am if I'm away
  trigger:
  - at: 09:30:00
    platform: time
  condition:
  - condition: state
    entity_id: cover.serena_r_roller_shade
    state: closed
  - condition: state
    entity_id: person.raspberrypisauce
    state: not_home
  action:
  - data:
      entity_id:
      - cover.serena_r_roller_shade
      - cover.serena_r_roller_shade_2
    service: cover.open_cover
- id: '1570381389931'
  alias: Shades - Turn on cool lights when shades open
  trigger:
  - entity_id: cover.serena_r_roller_shade
    platform: state
    to: open
  condition:
  - after: sunrise
    condition: sun
  - before: sunset
    before_offset: -02:00:00
    condition: sun
  - condition: zone
    entity_id: person.raspberrypisauce
    zone: zone.home
  action:
  - data:
      group_name: Common areas & bedroom
      scene_name: Afternoon
    service: hue.hue_activate_scene
- id: '1570429088603'
  alias: Bedroom Fan - Low [72 - 74]
  trigger:
  - above: '71.9'
    below: '74.1'
    entity_id: sensor.motion_sensor_temperature_measurement_2
    platform: numeric_state
  - entity_id: person.raspberrypisauce
    platform: state
    to: home
  condition:
  - above: '71.9'
    below: '74.1'
    condition: numeric_state
    entity_id: sensor.motion_sensor_temperature_measurement_2
  - condition: state
    entity_id: person.raspberrypisauce
    state: home
  - condition: state
    entity_id: fan.bedroom_fan
    state: 'off'
  action:
  - data:
      entity_id: fan.bedroom_fan
      speed: low
    service: fan.turn_on
- id: '1570429428645'
  alias: Bedroom Fan - Medium [75 - 78]
  trigger:
  - above: '74.9'
    below: '78.1'
    entity_id: sensor.motion_sensor_temperature_measurement_2
    platform: numeric_state
  - entity_id: person.raspberrypisauce
    platform: state
    to: home
  condition:
  - above: '74.9'
    below: '78.1'
    condition: numeric_state
    entity_id: sensor.motion_sensor_temperature_measurement_2
  - condition: state
    entity_id: person.raspberrypisauce
    state: home
  action:
  - data:
      entity_id: fan.bedroom_fan
      speed: medium
    service: fan.turn_on
- id: '1570430068737'
  alias: Bedroom Fan - High [79+)
  trigger:
  - above: '78.9'
    entity_id: binary_sensor.motion_sensor_motion_2
    platform: numeric_state
  - entity_id: person.raspberrypisauce
    platform: state
    to: home
  condition:
  - above: '78.9'
    condition: numeric_state
    entity_id: sensor.motion_sensor_temperature_measurement_2
  - condition: state
    entity_id: person.raspberrypisauce
    state: home
  action:
  - data:
      entity_id: fan.bedroom_fan
      speed: high
    service: fan.turn_on
- id: '1570688536245'
  alias: Lights - Turn off when I leave home
  trigger:
  - entity_id: person.raspberrypisauce
    from: home
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: light.all_indoor
    state: 'on'
  action:
  - data:
      entity_id: light.all_indoor
    service: light.turn_off
- id: '1570723343457'
  alias: Fans - Turn off when I leave
  trigger:
  - entity_id: person.raspberrypisauce
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      entity_id:
      - fan.bedroom_fan
      - fan.guest_bedroom_fan
    service: fan.turn_off
- id: '1570854881416'
  alias: Lock - Lock the front door if closed when I'm away
  trigger:
  - entity_id: person.raspberrypisauce
    from: home
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: lock.front_door_lock
    state: unlocked
  - condition: state
    entity_id: binary_sensor.front_door_contact
    state: 'off'
  action:
  - data:
      entity_id: lock.front_door_lock
    service: lock.lock
  - data:
      message: Looks like you left the front door unlocked. I've locked it for you.
      title: Front Door Locked
    service: notify.all_devices
- id: '1570855146802'
  alias: Lock - Lock the back door if closed when I'm away
  trigger:
  - entity_id: person.raspberrypisauce
    from: home
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: lock.back_door_lock
    state: unlocked
  - condition: state
    entity_id: binary_sensor.back_door_contact
    state: 'off'
  action:
  - data:
      entity_id: lock.back_door_lock
    service: lock.lock
  - data:
      message: Looks like you left the back door unlocked. I've locked it for you.
      title: Back Door Locked
    service: notify.all_devices
- id: '1570855325431'
  alias: Lock - Warn if I leave the front door open
  trigger:
  - entity_id: person.raspberrypisauce
    from: home
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: binary_sensor.front_door_contact
    state: 'on'
  action:
  - data:
      message: You've left the front door open! Go back home and close it.
      title: Front Door Open
    service: notify.all_devices
- id: '1570855443697'
  alias: Lock - Warn if I leave the back door open
  trigger:
  - entity_id: person.raspberrypisauce
    from: home
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: binary_sensor.back_door_contact
    state: 'on'
  action:
  - data:
      message: You've left the back door open! Go back home and close it.
      title: Back Door Open
    service: notify.all_devices
- id: '1572578924832'
  alias: Temperature - Alert when it's over 80F
  description: ''
  trigger:
  - above: '79.9'
    entity_id: sensor.condo_temperature
    platform: numeric_state
  condition: []
  action:
  - data:
      message: It's quite hot at the condo
      title: Temperature Alert
    service: notify.all_devices
- id: '1572579009006'
  alias: Temperature - Alert when it's below 65F
  description: ''
  trigger:
  - below: '65.1'
    entity_id: sensor.condo_temperature
    platform: numeric_state
  condition: []
  action:
  - data:
      message: It's quite cold at the condo
      title: Temperature Alert
    service: notify.all_devices
- id: '1572579879472'
  alias: Lights - Turn on guest bedroom with motion
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_sensor_motion_2
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.guest_bedroom
    state: 'off'
  action:
  - data_template:
      brightness: '{{ states.light.hallway_1.attributes.brightness }}'
      color_temp: '{{ states.light.hallway_1.attributes.color_temp }}'
    entity_id: light.guest_bedroom
    service: light.turn_on
- id: '1572579998069'
  alias: Lights - Turn off guest bedroom after inactivity
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_sensor_motion_2
    for: 00:05:00
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.guest_bedroom
    service: light.turn_off
- id: '1574050640483'
  alias: Christmas Lights - Outdoor - On at dusk
  description: ''
  trigger:
  - event: sunset
    offset: -00:10:00
    platform: sun
  condition: []
  action:
  - device_id: ed06766648784b24b475ced8a7c435bb
    domain: switch
    entity_id: switch.bedroom_window_lights
    type: turn_on
  - device_id: de7bfee3daec43ffb8c689d8e377478a
    domain: switch
    entity_id: switch.guest_bedroom_window_lights
    type: turn_on
  - device_id: aea6714a649243a69343941ed99f1c1b
    domain: switch
    entity_id: switch.living_room_window_lights
    type: turn_on
- id: '1574050716146'
  alias: Christmas Lights - Outdoor - Off at 4am
  description: ''
  trigger:
  - at: 04:00:00
    platform: time
  condition: []
  action:
  - device_id: ed06766648784b24b475ced8a7c435bb
    domain: switch
    entity_id: switch.bedroom_window_lights
    type: turn_off
  - device_id: de7bfee3daec43ffb8c689d8e377478a
    domain: switch
    entity_id: switch.guest_bedroom_window_lights
    type: turn_off
  - device_id: aea6714a649243a69343941ed99f1c1b
    domain: switch
    entity_id: switch.living_room_window_lights
    type: turn_off
- id: '1574067039121'
  alias: Christmas Lights - Living Room - 6 hour timer override
  description: The living room Christmas lights have a built in 6 hour timer. In order
    to ensure HA always has control over the light's state, power cycle the lights
    every 5.5 hours to reset its internal timer.
  trigger:
  - entity_id: switch.living_room_perimeter_lights
    for: 05:30:00
    platform: state
    to: 'on'
  condition: []
  action:
  - device_id: c98fbe1c32a04977981d4ed626e2432f
    domain: switch
    entity_id: switch.living_room_perimeter_lights
    type: turn_off
  - delay: 00:00:02
  - device_id: c98fbe1c32a04977981d4ed626e2432f
    domain: switch
    entity_id: switch.living_room_perimeter_lights
    type: turn_on
- id: '1574067136055'
  alias: Christmas Lights - Indoor - Turn off when away
  description: ''
  trigger:
  - entity_id: person.raspberrypisauce
    platform: state
    to: not_home
  condition: []
  action:
  - device_id: c98fbe1c32a04977981d4ed626e2432f
    domain: switch
    entity_id: switch.living_room_perimeter_lights
    type: turn_off
- id: '1574067318485'
  alias: Christmas Lights - Indoor - Turn on if home & sunset
  description: ''
  trigger:
  - entity_id: person.raspberrypisauce
    platform: state
    to: home
  - event: sunset
    offset: +00:10:00
    platform: sun
  condition:
  - condition: state
    entity_id: person.raspberrypisauce
    state: home
  - after: sunset
    after_offset: +00:10:00
    condition: sun
  action:
  - device_id: c98fbe1c32a04977981d4ed626e2432f
    domain: switch
    entity_id: switch.living_room_perimeter_lights
    type: turn_on
- id: '1574964598493'
  alias: Lights - On in the morning with motion
  description: ''
  trigger:
  - entity_id: binary_sensor.hallway_motion
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.master_bedroom
    state: 'on'
  - condition: sun
    after: sunrise
  - condition: time
    before: '12:00:00'
  - condition: state
    entity_id: light.hallway
    state: 'off'
  - condition: state
    entity_id: light.living_room
    state: 'off'
  action:
  - data:
      group_name: Common areas
      scene_name: Bright
    service: hue.hue_activate_scene
- id: '1575326973689'
  alias: Lights - Turn off bedroom after 10 minutes
  description: Only after 11am when I'm presumably awake, but before sunset, turn
    off the bedroom lights if there is no motion for a period of time.
  trigger:
  - entity_id: binary_sensor.motion_sensor_motion
    for: 00:10:00
    platform: state
    to: 'off'
  condition:
  - after: '11:00:00'
    condition: time
  - before: sunset
    condition: sun
  action:
  - data:
      entity_id: light.master_bedroom
    service: light.turn_off
- id: '1575529515498'
  alias: Living Room Fan - Map HA switch to on/off script
  description: ''
  trigger:
  - entity_id: input_boolean.living_room_fan_ir
    platform: state
    to: 'on'
  - entity_id: input_boolean.living_room_fan_ir
    platform: state
    to: 'off'
  condition: []
  action:
  - service: script.living_room_fan_on
- id: '1575750135185'
  alias: Lights - Turn on bedroom lights with motion
  description: During daylight hours, turn on the bedroom lights to match the hallway
    if there's motion.
  trigger:
  - entity_id: binary_sensor.motion_sensor_motion
    platform: state
    to: 'on'
  condition:
  - before: sunset
    before_offset: +01:00:00
    condition: sun
  - condition: state
    entity_id: light.master_bedroom
    state: 'off'
  - after: '11:00:00'
    condition: time
  action:
  - data_template:
      brightness: '{{ states.light.hallway_1.attributes.brightness }}'
      color_temp: '{{ states.light.hallway_1.attributes.color_temp }}'
    entity_id: light.master_bedroom
    service: light.turn_on
