- id: '1568784959927'
  alias: Match hallway lights to living room lights
  trigger:
  - entity_id: binary_sensor.hallway_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.living_room_ceiling_4
    state: 'on'
  action:
  - alias: ''
    service: light.turn_on
    entity_id:
    - light.hallway_1
    - light.hallway_2
    data_template:
      brightness: '{{ states.light.living_room_ceiling_4.attributes.brightness }}'
      color_temp: '{{ states.light.living_room_ceiling_4.attributes.color_temp }}'
- id: '1568831881438'
  alias: Outdoor lights - on at sunset
  trigger:
  - event: sunset
    offset: -00:45:00
    platform: sun
  condition: []
  action:
  - data:
      brightness: 254
      entity_id: light.outside
      rgb_color:
      - 255
      - 207
      - 120
    service: light.turn_on
- id: '1568831954351'
  alias: Outdoor lights - off at sunrise
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - data:
      entity_id: light.outside
    service: light.turn_off
- id: '1568832400745'
  alias: Shades - Close 15 minutes after sunset
  trigger:
  - event: sunset
    offset: +00:15:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: cover.serena_r_roller_shade
    service: cover.close_cover
  - data:
      entity_id: cover.serena_r_roller_shade_2
      position: 0
    service: cover.set_cover_position
- id: '1568834500654'
  alias: Computer - turn on weekday evenings when I come home
  trigger:
  - entity_id: person.raspberrypisauce
    for: 00:02:00
    from: away
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - after: '16:00:00'
    before: '23:59:59'
    condition: time
  - condition: state
    entity_id: switch.computer
    state: 'off'
  action:
  - data:
      entity_id: switch.computer
    service: switch.turn_on
