# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  customize: !include customize.yaml
  
zha_map:
  
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: https://pisauce.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# MQTT
mqtt:
  broker: 192.168.1.22
  client_id: home_assistant
  username: mqtt
  password: !secret mqtt_password

# Device tracker
device_tracker:
  - platform: synology_srm
    host: 192.168.1.1
    password: !secret synology_password
    new_device_defaults:
      track_new_devices: true

# Workday tracker
binary_sensor:
  - platform: workday
    country: US

# Eufy Vacuum
eufy_vacuum:
  devices:
  - name: Robovac
    address: 192.168.1.33
    access_token: !secret eufy_access_token
    id: !secret eufy_id
    type: T2118

# Enable wake on LAN
wake_on_lan:

# Log to MariaDB
recorder:
  db_url: !secret mariadb_connection_string
  purge_keep_days: 7

# Google Assistant
google_assistant:
  project_id: home-assistant-253907
  service_account: !include google_assistant_service_account.json
  report_state: true
  expose_by_default: false
  entity_config:
    cover.garage_door:
      expose: true
    cover.serena_r_roller_shade:
      expose: true
    cover.serena_r_roller_shade_2:
      expose: true
    fan.bedroom_fan:
      expose: true
    fan.guest_bedroom_fan:
      expose: true
    input_boolean.living_room_fan_ir:
      expose: true
    light.dining_room:
      expose: true
    light.guest_bedroom:
      expose: true
    light.hallway:
      expose: true
    light.kitchen:
      expose: true
    light.living_room:
      expose: true
    light.master_bedroom:
      expose: true
    lock.back_door_lock:
      expose: true
    lock.front_door_lock:
      expose: true
    script.1572070274974:
      expose: true
      name: Daytime lights
    script.lighting_scene_movie:
      expose: true
      name: Movie lights
    script.lighting_scene_dinner:
      expose: true
      name: Dinner lights
    script.lighting_scene_morning:
      expose: true
      name: Morning lights
    script.1572070321226:
      expose: true
      name: Afternoon lights
    script.1572070210780:
      expose: true
      name: Evening lights
    script.1572331520718:
      expose: true
      name: Night lights
    sensor.condo_temperature:
      expose: true
      aliases:
        - INSIDE_TEMPERATURE
        - TEMPERATURE_INSIDE
    sensor.bedroom_temperature:
      expose: true
    switch.air_purifier:
      expose: true
    switch.computer:
      expose: true
    switch.living_room_heater:
      expose: true
    switch.watch_chromecast:
      expose: true
    switch.watch_tv:
      expose: true

cover:
  - platform: mqtt
    name: "Garage door"
    command_topic: "garadget/Garage/command"
    state_topic: "garadget/Garage/status"
    state_open: "open"
    state_closed: "closed"
    payload_open: "open"
    payload_close: "close"
    value_template: '{{ value_json.status }}'

switch:
  - platform: wake_on_lan
    mac: "30:9c:23:ea:ab:d0"
    name: computer_wol
    host: 192.168.1.31
    broadcast_address: 192.168.1.255
  - platform: template
    switches:
      # Show air purifier low/med/high fan speed
      air_purifier_with_speed:
        friendly_name: Air purifier
        value_template: '{{ states.switch.air_purifier.state }}'
        icon_template: >-
          {% if is_state('switch.air_purifier', 'off') %}
            mdi:circle-off-outline
          {% elif states.sensor.air_purifier_power.state|float < 6 %}
            mdi:speedometer-slow
          {% elif states.sensor.air_purifier_power.state|float < 39 %}
            mdi:speedometer-medium
          {% else %}
            mdi:speedometer
          {% endif %}
        availability_template: >-
          {%- if not is_state('switch.air_purifier', 'unavailable') %}
            true
          {%- endif %}
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.air_purifier
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.air_purifier
    
      # Turn computer on and off
      computer:
        value_template: '{{ states.switch.computer_wol.state }}'
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.computer_wol
        turn_off:
          service: hassio.addon_stdin
          data:
            addon: core_rpc_shutdown
            input: PC
            
      # Harmony Hub - Watch TV
      watch_tv:
        friendly_name: "Watch TV"
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Watch TV') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'Watch TV'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'
  
      # Harmony Hub - Watch Chromecast
      watch_chromecast:
        friendly_name: "Watch Chromecast"
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Watch Chromecast') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'Watch Chromecast'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'
    
# Logitech Harmony Hub
remote:
  - platform: harmony
    name: Living Room
    host: 192.168.1.32
    
# Android Push Notifications
notify:
  - platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
  - platform: group
    name: all_devices
    services:
      - service: html5_anrdoid_mobile
      - service: html5_desktop_home
    
# Alerts
alert:
  bathroom_leak_sensor_water:
    name: bathroom_water_leak
    title: Leak Detected
    message: Water leak detected in the bathroom
    done_message: Bathroom is back to normal
    entity_id: binary_sensor.bathroom_leak_sensor
    state: 'on'
    repeat:
      - 5
      - 15
      - 60
    skip_first: false
    can_acknowledge: false
    notifiers:
      - all_devices
  kitchen_leak_sensor_water:
    name: kitchen_water_leak
    title: Leak Detected
    message: Water leak detected in the kitchen
    done_message: Kitchen is back to normal
    entity_id: binary_sensor.kitchen_leak_sensor
    state: 'on'
    repeat:
      - 5
      - 15
      - 60
    skip_first: false
    can_acknowledge: false
    notifiers:
      - all_devices

input_boolean:
  living_room_fan_ir:
    name: Living Room Fan
    initial: off
    icon: mdi:fan
  nightlight:
    name: Night light
    initial: off
    icon: mdi:lightbulb-outline
  vacuum_standby:
    name: Vacuum standby
    initial: off
    icon: mdi:robot-vacuum

sensor:
  # Average condo temperature sensor
  - platform: min_max
    type: mean
    name: Condo temperature
    entity_ids:
      - sensor.back_door_temperature
      - sensor.front_door_temperature
      - sensor.hallway_temperature
      - sensor.bedroom_temperature
      - sensor.guest_bedroom_temperature
  - platform: template
    sensors:
      # Bedroom fan speed
      fan_speed_bedroom:
        friendly_name: Bedroom fan speed
        value_template: "{{ state_attr('fan.bedroom_fan', 'speed') | lower }}"
        icon_template: >-
          {% if is_state('fan.bedroom_fan', 'off') %}
            mdi:circle-off-outline
          {% elif is_state_attr('fan.bedroom_fan', 'speed', 'low') %}
            mdi:speedometer-slow
          {% elif is_state_attr('fan.bedroom_fan', 'speed', 'medium') %}
            mdi:speedometer-medium
          {% else %}
            mdi:speedometer
          {% endif %}
        availability_template: >-
          {%- if not is_state('fan.bedroom_fan', 'unavailable') %}
            true
          {%- endif %}
      
      # Guest bedroom fan speed
      fan_speed_guest_bedroom:
        friendly_name: Guest bedroom fan speed
        value_template: "{{ state_attr('fan.guest_bedroom_fan', 'speed') | lower }}"
        icon_template: >-
          {% if is_state('fan.guest_bedroom_fan', 'off') %}
            mdi:circle-off-outline
          {% elif is_state_attr('fan.guest_bedroom_fan', 'speed', 'low') %}
            mdi:speedometer-slow
          {% elif is_state_attr('fan.guest_bedroom_fan', 'speed', 'medium') %}
            mdi:speedometer-medium
          {% else %}
            mdi:speedometer
          {% endif %}
        availability_template: >-
          {%- if not is_state('fan.guest_bedroom_fan', 'unavailable') %}
            true
          {%- endif %}
      
      # Living room fan state with proper capitalization
      fan_speed_living_room:
        friendly_name: Living room fan speed
        value_template: "{{ states('input_boolean.living_room_fan_ir') | lower }}"
      
      # Show air purifier low/med/high fan speed
      air_purifier_with_speed:
        friendly_name: Air purifier speed
        value_template: >-
          {% if is_state('switch.air_purifier', 'off') %}
            off
          {% elif states.sensor.air_purifier_power.state|float < 6 %}
            low
          {% elif states.sensor.air_purifier_power.state|float < 39 %}
            medium
          {% else %}
            high
          {% endif %}
        icon_template: >-
          {% if is_state('switch.air_purifier', 'off') %}
            mdi:circle-off-outline
          {% elif states.sensor.air_purifier_power.state|float < 6 %}
            mdi:speedometer-slow
          {% elif states.sensor.air_purifier_power.state|float < 39 %}
            mdi:speedometer-medium
          {% else %}
            mdi:speedometer
          {% endif %}
        availability_template: >-
          {%- if not is_state('switch.air_purifier', 'unavailable') %}
            true
          {%- endif %}
          
      security_status:
        value_template: >-
          {% if is_state("group.doors", "on") %}
            Open
          {%- elif is_state("group.locks", "unlocked") %}
            Unlocked
          {%- elif is_state("group.shades", "open") %}
            Visible
          {%- else %}
            Secure
          {%- endif %}
  - platform: waqi
    token: !secret waqi_api_key
    locations:
      - seattle

history:
  exclude:
    domains:
      - automation
      - media_player
      - script
    entities:
      - binary_sensor.garrett_padera_s_pixel_perfect_presence
      - binary_sensor.updater
      - light.common_areas_bedroom
      - light.dining_room_ceiling
      - light.discoagroup
      - light.discoagroupeven
      - light.discoagroupeven_2
      - light.discoagroupodd
      - light.guest_bedroom_1
      - light.guest_bedroom_2
      - light.guest_bedroom_3
      - light.guest_bedroom_4
      - light.hallway_1
      - light.hallway_2
      - light.kitchen_1
      - light.kitchen_2
      - light.living_room_ceiling_1
      - light.living_room_ceiling_2
      - light.living_room_ceiling_3
      - light.living_room_ceiling_4
      - light.living_room_ceiling_5
      - light.living_room_ceiling_6
      - light.master_bedroom_1
      - light.master_bedroom_2
      - light.master_bedroom_3
      - light.master_bedroom_4
      - light.master_bedroom_left
      - light.master_bedroom_right
      - light.outside_front_door
      - light.outside_summit
      - light.under_cabinet_sink
      - light.under_cabinet_sink_2
      - light.under_cabinet_stove
      - switch.computer_wol