
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: https://pisauce.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# MQTT
mqtt:
  broker: 192.168.1.22
  client_id: home_assistant
  username: mqtt
  password: XxUMi8yd3t

# Device tracker
device_tracker:
  - platform: synology_srm
    host: 192.168.1.1
    password: !secret synology_password
    new_device_defaults:
      track_new_devices: true

# Workday tracker
binary_sensor:
  - platform: workday
    country: US

# Eufy Vacuum
eufy_robovac:
  devices:
  - name: Mr Clean
    address: 192.168.1.33
    access_token: 2a5b6515f29e3313
    id: 81667806ecfabcab87f8
    type: T2118

# Enable wake on LAN
wake_on_lan:

# Log to MariaDB
recorder:
  db_url: !secret mariadb_connection_string

cover:
  - platform: mqtt
    name: "Garage door"
    command_topic: "garadget/Garage/command"
    state_topic: "garadget/Garage/status"
    state_open: "open"
    state_closed: "closed"
    payload_open: "open"
    payload_close: "close"
    value_template: '{{ value_json.status }}'

switch:
  - platform: wake_on_lan
    mac: "30:9c:23:ea:ab:d0"
    name: computer_wol
    host: 192.168.1.31
    broadcast_address: 192.168.1.255
  - platform: template
    switches:
      computer:
        value_template: '{{ states.switch.computer_wol.state }}'
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.computer_wol
        turn_off:
          service: hassio.addon_stdin
          data:
            addon: core_rpc_shutdown
            input: PC
            
      # Harmony Hub - Watch TV
      watch_tv:
        friendly_name: "Watch TV"
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Watch TV') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'Watch TV'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'
  
      # Harmony Hub - Watch Chromecast
      watch_chromecast:
        friendly_name: "Watch Chromecast"
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Watch Chromecast') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'Watch Chromecast'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'
    
# Logitech Harmony Hub
remote:
  - platform: harmony
    name: Living Room
    host: 192.168.1.32
    
# Android Push Notifications
notify:
  - platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
  - platform: group
    name: all_devices
    services:
      - service: html5_anrdoid_mobile
      - service: html5_desktop_home
    
# Alerts
alert:
  bathroom_leak_sensor_water:
    name: bathroom_water_leak
    title: Leak Detected
    message: Water leak detected in the bathroom
    done_message: Bathroom is back to normal
    entity_id: binary_sensor.bathroom_leak_sensor_water
    state: 'on'
    repeat:
      - 5
      - 15
      - 60
    skip_first: false
    can_acknowledge: false
    notifiers:
      - all_devices
  kitchen_leak_sensor_water:
    name: kitchen_water_leak
    title: Leak Detected
    message: Water leak detected in the kitchen
    done_message: Kitchen is back to normal
    entity_id: binary_sensor.kitchen_leak_sensor_water
    state: 'on'
    repeat:
      - 5
      - 15
      - 60
    skip_first: false
    can_acknowledge: false
    notifiers:
      - all_devices

input_boolean:
  living_room_fan_ir:
    name: Living Room Fan
    initial: off
    icon: mdi:fan
  nightlight:
    name: Night light
    initial: off
    icon: mdi:lightbulb-outline

sensor:
  # Average condo temperature sensor
  - platform: min_max
    type: mean
    name: Condo temperature
    entity_ids:
      - sensor.back_door_temperature_measurement
      - sensor.front_door_temperature_measurement
      - sensor.hallway_temperature_measurement
      - sensor.motion_sensor_temperature_measurement
      - sensor.motion_sensor_temperature_measurement_2
    
history:
  exclude:
    domains:
      - automation
      - media_player
    entities:
      - binary_sensor.garrett_padera_s_pixel_perfect_presence
      - binary_sensor.updater
      - light.common_areas_bedroom
      - light.dining_room_ceiling
      - light.discoagroup
      - light.discoagroupeven
      - light.discoagroupeven_2
      - light.discoagroupodd
      - light.guest_bedroom_1
      - light.guest_bedroom_2
      - light.guest_bedroom_3
      - light.guest_bedroom_4
      - light.hallway_1
      - light.hallway_2
      - light.kitchen_1
      - light.kitchen_2
      - light.living_room_ceiling_1
      - light.living_room_ceiling_2
      - light.living_room_ceiling_3
      - light.living_room_ceiling_4
      - light.living_room_ceiling_5
      - light.living_room_ceiling_6
      - light.master_bedroom_1
      - light.master_bedroom_2
      - light.master_bedroom_3
      - light.master_bedroom_4
      - light.master_bedroom_left
      - light.master_bedroom_right
      - light.outside_front_door
      - light.outside_summit
      - light.under_cabinet_sink
      - light.under_cabinet_sink_2
      - light.under_cabinet_stove
      - switch.computer_wol